"""addded dashboard logic

Revision ID: 1cfae0b8f696
Revises: f0ea025fefce
Create Date: 2025-05-26 15:04:49.252361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfae0b8f696'
down_revision: Union[str, None] = 'f0ea025fefce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('auto_mobile_data', sa.Column('dashboard_id', sa.String(length=36), nullable=True))
    op.alter_column('auto_mobile_data', 'invoice_id',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_foreign_key(None, 'auto_mobile_data', 'dashboards', ['dashboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auto_mobile_data', type_='foreignkey')
    op.alter_column('auto_mobile_data', 'invoice_id',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_column('auto_mobile_data', 'dashboard_id')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
