"""Use UUIDs for primary keys

Revision ID: 2e337ec850a1
Revises: 
Create Date: 2025-05-08 13:22:02.242884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2e337ec850a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('country', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_country'), 'categories', ['country'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('brands',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('country', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('category', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_category'), 'brands', ['category'], unique=False)
    op.create_index(op.f('ix_brands_country'), 'brands', ['country'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('data_points',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('country', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('category', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('brand', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('metric', sa.String(length=255), nullable=True),
    sa.Column('metric_category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_brand'), 'data_points', ['brand'], unique=False)
    op.create_index(op.f('ix_data_points_category'), 'data_points', ['category'], unique=False)
    op.create_index(op.f('ix_data_points_country'), 'data_points', ['country'], unique=False)
    op.create_index(op.f('ix_data_points_id'), 'data_points', ['id'], unique=False)
    op.create_index(op.f('ix_data_points_metric_category'), 'data_points', ['metric_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_points_metric_category'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_country'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_category'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_brand'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_country'), table_name='brands')
    op.drop_index(op.f('ix_brands_category'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_country'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
