"""added the unit in it

Revision ID: 9a4ec9c79f43
Revises: 2e337ec850a1
Create Date: 2025-05-08 14:31:58.296148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4ec9c79f43'
down_revision: Union[str, None] = '2e337ec850a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_points', sa.Column('unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_points', 'unit')
    # ### end Alembic commands ###
