"""create automobile table

Revision ID: f0ea025fefce
Revises: 
Create Date: 2025-05-22 08:48:40.919305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ea025fefce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_mobile_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('oem_name', sa.String(), nullable=True),
    sa.Column('dealer_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('vehicle_segment', sa.String(), nullable=True),
    sa.Column('vehicle_model', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('year', sa.BigInteger(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('engine_displacement_cc', sa.BigInteger(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('type_of_fuel_used_postsale', sa.String(), nullable=True),
    sa.Column('range_km', sa.Float(), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('charging_time_hours', sa.Float(), nullable=True),
    sa.Column('competitor_model_name', sa.String(), nullable=True),
    sa.Column('competitor_oem', sa.String(), nullable=True),
    sa.Column('competitor_price', sa.BigInteger(), nullable=True),
    sa.Column('market_share_in_region', sa.Float(), nullable=True),
    sa.Column('salesperson_name', sa.String(), nullable=True),
    sa.Column('units_sold', sa.BigInteger(), nullable=True),
    sa.Column('unit_price', sa.BigInteger(), nullable=True),
    sa.Column('discount_offered', sa.BigInteger(), nullable=True),
    sa.Column('final_price_after_discount', sa.Float(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('finance_opted_yesno', sa.String(), nullable=True),
    sa.Column('financing_partner', sa.String(), nullable=True),
    sa.Column('exchange_vehicle_offered', sa.String(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('promotion_scheme_applied', sa.String(), nullable=True),
    sa.Column('accessories_bundle', sa.String(), nullable=True),
    sa.Column('free_services_offered', sa.BigInteger(), nullable=True),
    sa.Column('nps_customer_feedback', sa.BigInteger(), nullable=True),
    sa.Column('complaint_registered_yn', sa.String(), nullable=True),
    sa.Column('delivery_rating_15', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_mobile_data')
    # ### end Alembic commands ###
